// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz81TdHkqQCGT6Bhx7i8dy5iNpk9I8FKY',
    appId: '1:1090189276977:web:74166c02f23bf9aa8e2210',
    messagingSenderId: '1090189276977',
    projectId: 'rentapp-f1866',
    authDomain: 'rentapp-f1866.firebaseapp.com',
    storageBucket: 'rentapp-f1866.appspot.com',
    measurementId: 'G-NPQ4WHXC3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQRcjBhmdVQ8pC5fQI_zHzaJuaOsnmFFA',
    appId: '1:1090189276977:android:98282f94916291558e2210',
    messagingSenderId: '1090189276977',
    projectId: 'rentapp-f1866',
    storageBucket: 'rentapp-f1866.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfIuutQuNsDUdqAo7WIHxZVU0Mdqg8t6A',
    appId: '1:1090189276977:ios:77270d7abfac56078e2210',
    messagingSenderId: '1090189276977',
    projectId: 'rentapp-f1866',
    storageBucket: 'rentapp-f1866.appspot.com',
    iosBundleId: 'com.example.rentapp2',
  );
}
